server:
  port: 8080
  spring:
    application:
      name: SaadTechStore

      datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/store_tech}
        username: ${SPRING_DATASOURCE_USERNAME:saadad}
        password: ${SPRING_DATASOURCE_PASSWORD:saad2004}
        driver-class-name: org.postgresql.Driver
        hikari:
          maximum-pool-size: 10
          minimum-idle: 2
          connection-timeout: 20000
          idle-timeout: 300000

          jpa:
            hibernate:
              ddl-auto: update
            show-sql: false